---
title: "DataVisualization - Fire Incident Dispatch Data Analysis"
author: "Zuliani Riccardo"
date: "5/1/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/ricca/Desktop/UNI/Magistrale/Anno3/Statistical_Inference_and_Learning/SIL Projcet/Statistical_Inference_Learning_Project/Fire_Incident_Dispatch_Analysis")
```
# Dataset
I use the fire incident dispach from opendata of NewYork

# Loading Packages
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(mapview)
library(sf)
library(geojsonio)
library(leaflet) 
library(broom)
library(plotly)

#library(rmapzen)
#options(RMAPZEN_SEARCH_HOST = "geosearch.planninglabs.nyc")
#Sys.setenv("MAPZEN_KEY" = NA)
#mz_set_search_host_nyc_geosearch()


#library(devtools)
#install_github('ramnathv/rCharts')
```


```{r}
fire_data <- read.csv("datasets/Fire_Incident_Dispatch_Data_last_50k.csv")
alarm_box_loc <- read.csv("datasets/Alarm_Box_Locations.csv")
firefighter_stations <- read.csv("datasets/fdny-firehouse-listing.csv")
```

```{r}
fire_data$ALARM_BOX_NUMBER <- as.character(fire_data$ALARM_BOX_NUMBER)
fire_data$INCIDENT_BOROUGH <- as.factor(fire_data$INCIDENT_BOROUGH)
fire_data$INCIDENT_CLASSIFICATION_GROUP <- as.factor(fire_data$INCIDENT_CLASSIFICATION_GROUP)
 
fire_data <- fire_data %>% rename(al_number = ALARM_BOX_NUMBER, borough = INCIDENT_BOROUGH, al_location = ALARM_BOX_LOCATION, incident_class = INCIDENT_CLASSIFICATION_GROUP)

firefighter_stations$Borough <- as.factor(firefighter_stations$Borough)
firefighter_stations <- firefighter_stations %>% rename(borough = Borough)

alarm_box_loc_new <- alarm_box_loc %>% select(BOROBOX, LATITUDE, LONGITUDE) %>% 
                        rename(al_number = BOROBOX, lat = LATITUDE, lon = LONGITUDE)

fire_data <- fire_data %>%
  mutate(al_number = str_pad(al_number, width = 4, pad = "0"))


fire_data$total_unit_assigned <- fire_data$ENGINES_ASSIGNED_QUANTITY + fire_data$LADDERS_ASSIGNED_QUANTITY + fire_data$OTHER_UNITS_ASSIGNED_QUANTITY

```




```{r}
fire_data_new <- fire_data %>%
  mutate(al_number = case_when(
    borough == "BRONX" ~ paste0("X", al_number),
    borough == "BROOKLYN" ~ paste0("B", al_number),
    borough == "MANHATTAN" ~ paste0("M", al_number),
    borough == "QUEENS" ~ paste0("Q", al_number),
    borough == "RICHMOND / STATEN ISLAND" ~ paste0("R", al_number),
    TRUE ~ al_number
  ))
```


```{r}
fire_data_merged <- merge(fire_data_new, alarm_box_loc_new, by = "al_number", all.x = TRUE)

fire_data_merged <- na.omit(fire_data_merged)
firefighter_stations <- na.omit(firefighter_stations)
```


```{r}
alarm_inc_count <- fire_data_merged %>%
                    group_by(al_number, lat, lon, al_location) %>%
                    summarise(Count = n()) %>%
                    rename(incident_count = Count)

alarm_inc_count_sdf <- st_as_sf(alarm_inc_count, coords = c("lon", "lat"), crs = 4326)
```



```{r}
stations_borough <- firefighter_stations %>%
                    group_by(borough) %>%
                    summarise(Count = n()) %>%
                    rename(number_of_stations = Count)
```



```{r}
count_inc_brough <- count(fire_data_merged, borough)
count_inc_brough <- count_inc_brough %>% rename(incident_count = n)
count_inc_brough <- count_inc_brough %>% mutate(borough = recode_factor(borough, "BRONX" = "Bronx", "BROOKLYN" = "Brooklyn", "MANHATTAN" = "Manhattan", "QUEENS" = "Queens", "RICHMOND / STATEN ISLAND" = "Staten Island"))

stations_borough$incident_per_station <- round(count_inc_brough$incident_count / stations_borough$number_of_stations, digits = 3)

count_inc_brough <- merge(count_inc_brough, stations_borough, by="borough")
```


```{r}
firefighter_stations <- firefighter_stations %>% rename(lat = Latitude, lon = Longitude)
firefighter_stations_sdf <- st_as_sf(firefighter_stations, coords = c("lon", "lat"), crs = 4326)
head(firefighter_stations_sdf)
```





Downloand of the GEO JSON



```{r}
geojson_newyork <- geojson_read("datasets/NYC_BoroughBoundaries.geojson",  what = "sp")
geojson_newyork <- setNames(geojson_newyork, c("borough_code", "borough", "shape_area", "shape_leng"))
geojson_newyork$borough <- as.factor(geojson_newyork$borough)
geojson_newyork$borough_code <- NULL
head(geojson_newyork)
```





```{r}
geojson_newyork@data = data.frame(geojson_newyork@data, count_inc_brough[match(geojson_newyork@data$borough, count_inc_brough$borough),])
geojson_newyork@data$borough.1 <- NULL
```



```{r}
mapview(list(firefighter_stations_sdf, geojson_newyork),
        zcol = list(NULL, "incident_count"),
        legend = list(FALSE, TRUE),
        homebutton = list(FALSE, TRUE), layer.name = list(NULL, "indicents_number"), alpha.regions = 0.5, aplha = 1)
```


```{r}
mapview(list(alarm_inc_count_sdf, geojson_newyork),
        zcol = list("incident_count", "borough"),
        legend = list(TRUE, TRUE),
        homebutton = list(TRUE, TRUE),
        layer.name = list("incident_count", "brorough"),
        alpha.regions = list(0.7, 0.4), 
        aplha = list(1, 0.5))
```


distribution of incident per incident class
```{r}
alarm_inc_bor_class_count <- fire_data_new %>%
                              group_by(incident_class, al_number, borough) %>%
                              summarise(Count = n())

ggplot(data=alarm_inc_bor_class_count, aes(x=borough, y=Count, fill=incident_class)) +
    geom_bar(stat="identity", position=position_dodge())
```



```{r}
ggplot(fire_data, aes(x = borough, y = INCIDENT_RESPONSE_SECONDS_QY, color = incident_class)) +  # ggplot function
  geom_boxplot()
```



```{r}
fire_data[which.max(fire_data$INCIDENT_RESPONSE_SECONDS_QY), ]
```




```{r}
ggplot(fire_data, aes(x = borough, y = INCIDENT_TRAVEL_TM_SECONDS_QY, color = incident_class)) +  # ggplot function
  geom_boxplot()
```



```{r}
ggplot(fire_data, aes(x = borough, y = ENGINES_ASSIGNED_QUANTITY, color = incident_class)) +  # ggplot function
  geom_boxplot()
```

```{r}
fire_data %>% arrange(desc(ENGINES_ASSIGNED_QUANTITY)) %>% slice(1:2)
```

09/16/2023 06:59:35 PM, structural fires, source incident phone, url of the incident https://www.cbsnews.com/newyork/news/gravesend-brooklyn-fire-injuries/
09/24/2023 12:05:21 AM, structural fires, source incident phone, url of the incident https://abc7ny.com/three-injured-in-fire-bedford-stuyvesant-beford-stuyvesant-brooklyn-fdny/13823430/

```{r}
ggplot(fire_data, aes(x = borough, y = LADDERS_ASSIGNED_QUANTITY, color = incident_class)) +  # ggplot function
  geom_boxplot()
```

```{r}
fire_data %>% arrange(desc(LADDERS_ASSIGNED_QUANTITY)) %>% slice(1:2)
```

Same incidents of before

```{r}
ggplot(fire_data, aes(x = borough, y = OTHER_UNITS_ASSIGNED_QUANTITY, color = incident_class)) +  # ggplot function
  geom_boxplot()
```

```{r}
fire_data %>% arrange(desc(OTHER_UNITS_ASSIGNED_QUANTITY)) %>% slice(1:2)
```

Same incidents of before



```{r}
ggplot(fire_data, aes(x = borough, y = total_unit_assigned, color = incident_class)) +  # ggplot function
  geom_boxplot()
```

```{r}
fire_data %>% arrange(desc(total_unit_assigned)) %>% slice(1:2)
```

Same incidents of before



```{r}

source_al_borough_class <- fire_data %>%
                            group_by(ALARM_SOURCE_DESCRIPTION_TX, incident_class, borough) %>%
                            summarise(Count = n()) %>%
                            rename(incidents_number = Count)


ggplot(source_al_borough_class, aes(x = borough, y = incidents_number, color = ALARM_SOURCE_DESCRIPTION_TX)) +  # ggplot function
  geom_boxplot()
```

